# Generated by Django 2.2.6 on 2019-11-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='automodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=20)),
                ('doc', models.CharField(max_length=20)),
                ('nur', models.CharField(max_length=20)),
            ],
        ),
    ]
